import { BaseRepository, type DbClient } from "./base.repository";
import type { Tables, TablesInsert } from "@/types/database";

type TimeBlock = Tables<"time_blocks">;
type TimeBlockInsert = TablesInsert<"time_blocks">;
type UserGoal = Tables<"user_goals">;
type FocusSession = Tables<"focus_sessions">;
type CaptureItem = Tables<"capture_items">;
type ScratchpadItem = Tables<"scratchpad_items">;
type DailyPlan = Tables<"daily_plans">;

export class TimeBlocksRepository extends BaseRepository<"time_blocks"> {
  constructor(client: DbClient) {
    super(client, "time_blocks");
  }

  async findByDate(userId: string, date: string): Promise<TimeBlock[]> {
    const { data, error } = await this.query
      .select("*")
      .eq("user_id", userId)
      .eq("date", date)
      .order("start_time");
    if (error) throw error;
    return (data ?? []) as TimeBlock[];
  }

  async findByDateRange(userId: string, from: string, to: string): Promise<TimeBlock[]> {
    const { data, error } = await this.query
      .select("*")
      .eq("user_id", userId)
      .gte("date", from)
      .lte("date", to)
      .order("date")
      .order("start_time");
    if (error) throw error;
    return (data ?? []) as TimeBlock[];
  }

  async updateStatus(
    id: string,
    status: TimeBlock["status"],
    extra?: Partial<Pick<TimeBlock, "actual_start_at" | "actual_end_at" | "actual_minutes" | "interruptions" | "focus_score">>,
  ): Promise<TimeBlock> {
    return this.update(id, { status, updated_at: new Date().toISOString(), ...extra });
  }

  /** Inserts many blocks in one round-trip; returns them. */
  async bulkCreate(rows: TimeBlockInsert[]): Promise<TimeBlock[]> {
    if (rows.length === 0) return [];
    const { data, error } = await this.query.insert(rows).select("*");
    if (error) throw error;
    return (data ?? []) as TimeBlock[];
  }

  /**
   * Removes the planner's own not-yet-started blocks for a date so a re-plan can
   * rewrite them, while leaving manual/locked commitments and any block already
   * started or completed untouched.
   */
  async clearAutoGenerated(userId: string, date: string): Promise<void> {
    const { error } = await this.query
      .delete()
      .eq("user_id", userId)
      .eq("date", date)
      .eq("auto_generated", true)
      .eq("locked", false)
      .in("status", ["planned", "postponed"]);
    if (error) throw error;
  }

  /** Blocks that must be scheduled around — meetings, manual, or locked. */
  async findFixedByDate(userId: string, date: string): Promise<TimeBlock[]> {
    const { data, error } = await this.query
      .select("*")
      .eq("user_id", userId)
      .eq("date", date)
      .or("locked.eq.true,auto_generated.eq.false")
      .order("start_time");
    if (error) throw error;
    return (data ?? []) as TimeBlock[];
  }
}

export class DailyPlansRepository extends BaseRepository<"daily_plans"> {
  constructor(client: DbClient) {
    super(client, "daily_plans");
  }

  async findByDate(userId: string, date: string): Promise<DailyPlan | null> {
    const { data, error } = await this.query
      .select("*")
      .eq("user_id", userId)
      .eq("plan_date", date)
      .maybeSingle();
    if (error) throw error;
    return (data as DailyPlan | null) ?? null;
  }

  async findRecent(userId: string, limit = 7): Promise<DailyPlan[]> {
    const { data, error } = await this.query
      .select("*")
      .eq("user_id", userId)
      .order("plan_date", { ascending: false })
      .limit(limit);
    if (error) throw error;
    return (data ?? []) as DailyPlan[];
  }

  /** Upserts the plan header for a (user, date) — one row per day. */
  async upsert(
    userId: string,
    date: string,
    patch: Omit<TablesInsert<"daily_plans">, "id" | "user_id" | "plan_date" | "created_at">,
  ): Promise<DailyPlan> {
    const { data, error } = await this.query
      .upsert(
        { user_id: userId, plan_date: date, updated_at: new Date().toISOString(), ...patch },
        { onConflict: "user_id,plan_date", ignoreDuplicates: false },
      )
      .select("*")
      .single();
    if (error) throw error;
    return data as DailyPlan;
  }
}

export class UserGoalsRepository extends BaseRepository<"user_goals"> {
  constructor(client: DbClient) {
    super(client, "user_goals");
  }

  async findActive(userId: string): Promise<UserGoal[]> {
    const { data, error } = await this.query
      .select("*")
      .eq("user_id", userId)
      .eq("status", "active")
      .order("horizon")
      .order("created_at");
    if (error) throw error;
    return (data ?? []) as UserGoal[];
  }

  async findByHorizon(userId: string, horizon: UserGoal["horizon"]): Promise<UserGoal[]> {
    const { data, error } = await this.query
      .select("*")
      .eq("user_id", userId)
      .eq("horizon", horizon)
      .neq("status", "abandoned")
      .order("created_at");
    if (error) throw error;
    return (data ?? []) as UserGoal[];
  }

  async updateProgress(id: string, progress: number): Promise<UserGoal> {
    return this.update(id, {
      progress: Math.min(100, Math.max(0, progress)),
      status: progress >= 100 ? "completed" : undefined,
      updated_at: new Date().toISOString(),
    });
  }
}

export class FocusSessionsRepository extends BaseRepository<"focus_sessions"> {
  constructor(client: DbClient) {
    super(client, "focus_sessions");
  }

  async findByDateRange(userId: string, from: string, to: string): Promise<FocusSession[]> {
    const { data, error } = await this.query
      .select("*")
      .eq("user_id", userId)
      .gte("started_at", from)
      .lte("started_at", to)
      .order("started_at", { ascending: false });
    if (error) throw error;
    return (data ?? []) as FocusSession[];
  }

  async findToday(userId: string): Promise<FocusSession[]> {
    const start = new Date();
    start.setHours(0, 0, 0, 0);
    const end = new Date();
    end.setHours(23, 59, 59, 999);
    return this.findByDateRange(userId, start.toISOString(), end.toISOString());
  }

  async complete(id: string, actualMinutes: number, focusScore: number): Promise<FocusSession> {
    return this.update(id, {
      ended_at: new Date().toISOString(),
      completed: true,
      actual_minutes: actualMinutes,
      focus_score: focusScore,
    });
  }
}

export class CaptureItemsRepository extends BaseRepository<"capture_items"> {
  constructor(client: DbClient) {
    super(client, "capture_items");
  }

  async findPending(userId: string): Promise<CaptureItem[]> {
    const { data, error } = await this.query
      .select("*")
      .eq("user_id", userId)
      .eq("status", "pending")
      .order("captured_at", { ascending: false });
    if (error) throw error;
    return (data ?? []) as CaptureItem[];
  }

  async dismiss(id: string): Promise<void> {
    await this.update(id, { status: "dismissed" });
  }

  async process(id: string): Promise<void> {
    await this.update(id, { status: "processed", processed_at: new Date().toISOString() });
  }
}

export class ScratchpadItemsRepository extends BaseRepository<"scratchpad_items"> {
  constructor(client: DbClient) {
    super(client, "scratchpad_items");
  }

  async findByUser(userId: string): Promise<ScratchpadItem[]> {
    const { data, error } = await this.query
      .select("*")
      .eq("user_id", userId)
      .or("expires_at.is.null,expires_at.gt." + new Date().toISOString())
      .order("pinned", { ascending: false })
      .order("created_at", { ascending: false });
    if (error) throw error;
    return (data ?? []) as ScratchpadItem[];
  }

  async togglePin(id: string, pinned: boolean): Promise<ScratchpadItem> {
    return this.update(id, { pinned, updated_at: new Date().toISOString() });
  }
}
