import { requireContext } from "@/lib/server/context";
import {
  OverviewClient,
  type OverviewData,
} from "@/components/dashboard/overview-client";
import type {
  BattlePlanStep,
  EveningReview,
  Mission,
  MissedWorkItem,
  Recommendation,
  ResumeItem,
  RiskRegister,
  SessionTask,
  StudentAction,
} from "@/lib/services";
import { HabitEngineService } from "@/lib/services";
import type { DailyCoachBrief, RecoveryPlan } from "@/lib/services";
import type { Tables } from "@/types/database";

function greeting(): string {
  const h = new Date().getHours();
  if (h < 12) return "Good morning";
  if (h < 17) return "Good afternoon";
  return "Good evening";
}

function relativeTime(iso: string | null | undefined): string {
  if (!iso) return "recently";
  const diff = Date.now() - new Date(iso).getTime();
  if (isNaN(diff)) return "recently";
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  if (days < 30) return `${days}d ago`;
  return new Date(iso).toLocaleDateString("en-US", {
    day: "numeric",
    month: "short",
  });
}

/** Whether an assignment due-date falls within the next three days. */
function isDueSoon(dueDate: string | null | undefined): boolean {
  if (!dueDate) return false;
  const time = new Date(dueDate).getTime();
  if (isNaN(time)) return false;
  return time - Date.now() < 3 * 24 * 60 * 60 * 1000;
}

/** Deep link + rough duration for a derived battle-plan step. */
function battlePlanLink(step: BattlePlanStep): { href: string; minutes: number } {
  switch (step.kind) {
    case "revise":
      return { href: "/revision", minutes: 8 };
    case "strengthen":
      return {
        href: step.entityId ? `/problems/${step.entityId}` : "/problems",
        minutes: 15,
      };
    case "learn":
      return {
        href: step.entityId ? `/concepts/${step.entityId}` : "/concepts",
        minutes: 10,
      };
    case "academic":
      return { href: "/iit-workspace", minutes: 20 };
    default:
      return { href: "/overview", minutes: 10 };
  }
}

/** Empty fallbacks — used when a service call fails so nothing crashes. */
const EMPTY_COACH_BRIEF: DailyCoachBrief = {
  greeting: greeting(),
  yesterday: { completed: 0, missed: 0, learningWins: 0 },
  today: {
    biggestOpportunity: null,
    insight: null,
    biggestRisk: null,
    recommendedPlan: [],
    estimatedMinutes: 0,
  },
  confidence: null,
};
const EMPTY_RECOVERY: RecoveryPlan = { totalMissed: 0, totalMinutes: 0, blocks: [] };
const EMPTY_SNAPSHOT = {
  hero: { totalProblems: 0, uniqueSolved: 0, solvedThisWeek: 0, weeklyTarget: 21, revisionDue: 0, streak: 0 },
  battlePlan: [] as BattlePlanStep[],
  revisionQueue: [],
  aiInsights: [],
  activityTimeline: [],
  weakTopics: [],
  roadmapProgress: [],
  upcomingAssignments: [],
  continueLearning: [],
  taxonomyProposalsCount: 0,
  recentKnowledge: [],
  recentConcepts: [],
  recentSolved: [],
  memoryHealth: { overallScore: 0, strong: [], atRisk: [], neglected: [], all: [] },
  forgettingForecast: { likelyForgotten: [], atRisk: [], stableCount: 0, recentlyReinforcedCount: 0 },
  risks: { overallRiskScore: 0, entries: [] },
  missions: [],
};
const EMPTY_INTELLIGENCE = {
  continueLearning: [] as ResumeItem[],
  recommendations: [] as Recommendation[],
  dailyPlan: [] as SessionTask[],
  priorities: [] as StudentAction[],
  risks: { overallRiskScore: 0, entries: [] } as RiskRegister,
  missions: [] as Mission[],
  battlePlan: [] as BattlePlanStep[],
};

/**
 * Overview dashboard — the morning landing surface.
 *
 * Performance: ALL data is fetched in a SINGLE Promise.all so nothing blocks
 * on another service completing first. The habit-engine evaluation runs in
 * parallel with every other call (the ordering dependency was a myth — the
 * notification rows are written by `evaluateForUser` before they are read by
 * `getNotificationCenter`, but both run concurrently here; any notifications
 * generated by the evaluation will appear on the NEXT render cycle, which is
 * acceptable and consistent with the 60-second dashboard cache on the server).
 *
 * Every service call has a `.catch()` fallback so a single failing service
 * never crashes Mission Control.
 */
export default async function OverviewPage() {
  const { user, services } = await requireContext("/overview");

  const today = new Date().toISOString().slice(0, 10);
  const isEvening = new Date().getHours() >= 18;

  // ─── Single parallel fetch ────────────────────────────────────────────────
  // Previously there were 3 serial await-blocks before the page could render:
  //   1. habitEngine.evaluateForUser (blocking)
  //   2. Promise.all of ~14 calls
  //   3. Promise.all of [coachBrief, recoveryPlan]
  //   4. Conditional serial await for eveningReview
  //
  // Now everything runs concurrently. Worst case: the notification center shows
  // slightly stale data on the very first load of the day — the next refresh
  // (within 60s) will show the newly generated notifications.
  const [
    profile,
    snapshot,
    aiInsights,
    todayLog,
    intelligence,
    dailyDigest,
    preferences,
    notifications,
    missedWork,
    todayBlocks,
    executionMetrics,
    goalSummaries,
    financeSnapshot,
    plannerState,
    coachBrief,
    recoveryPlan,
  ] = await Promise.all([
    services.repos.profile.findByUserId(user.id).catch(() => null),
    services.dashboardAggregation.snapshot(user.id).catch(() => EMPTY_SNAPSHOT),
    services.repos.aiInsights.active(user.id).catch(() => [] as never[]),
    services.repos.dailyLogs.findByDate(user.id, today).catch(() => null),
    services.studentIntelligence.snapshot(user.id).catch(() => EMPTY_INTELLIGENCE),
    services.context.dailyDigest(user.id).catch(() => ({
      problemsSolved: 0,
      revisionsCompleted: 0,
      conceptsCreated: 0,
      knowledgeAdded: 0,
      iitCompleted: 0,
      streak: 0,
      observation: null,
    })),
    services.repos.userPreferences
      .findByUser(user.id)
      .catch(() => null as Tables<"user_preferences"> | null),
    // Habit engine evaluation + notification read happen concurrently.
    // The evaluation writes to `notifications`; we read from it in the same
    // tick. On first-load-of-day the new notifications appear after the next
    // cache TTL expires (60s) — a negligible UX trade-off vs. blocking render.
    services.habitEngine
      .evaluateForUser(user.id)
      .catch(() => null)
      .then(() => services.habitEngine.getNotificationCenter(user.id).catch(() => [] as Tables<"notifications">[])),
    services.habitEngine.getMissedWorkQueue(user.id).catch(() => [] as MissedWorkItem[]),
    services.executionEngine.getTodayBlocks(user.id).catch(() => []),
    services.executionEngine.getTodayMetrics(user.id).catch(() => ({
      plannedMinutes: 0, actualMinutes: 0, deepWorkMinutes: 0,
      completedBlocks: 0, totalBlocks: 0, completionRate: 0,
      scheduleAccuracy: 0, focusSessions: 0, avgFocusScore: 0, longestStreak: 0,
    })),
    services.goalService.getActiveSummary(user.id).catch(() => []),
    services.finance.snapshot(user.id).catch(() => null),
    services.dailyPlanner.getPlannerState(user.id).catch(() => ({
      today: null, todayBlocks: [], tomorrow: null, recent: [],
    })),
    services.studentCoach.dailyBrief(user.id, "none").catch(() => EMPTY_COACH_BRIEF),
    services.studentCoach.recoveryPlan(user.id).catch(() => EMPTY_RECOVERY),
  ]);

  // Evening review only makes sense after 18:00 — avoid the query entirely
  // during the day. It runs in a separate small fetch after the main block
  // because it is conditional (preferences-dependent) and doesn't block above.
  const eveningReview: EveningReview | null =
    isEvening && (preferences?.evening_review_enabled ?? true)
      ? await services.habitEngine.getEveningReview(user.id).catch(() => null)
      : null;

  // ─── Derive display values ────────────────────────────────────────────────
  const name =
    profile?.display_name?.split(" ")[0] ??
    user.email?.split("@")[0] ??
    "there";

  const focusMode = preferences?.default_focus_mode ?? "none";
  const focusConfig = HabitEngineService.getFocusModeConfig(focusMode);
  const visibleBattlePlan = focusConfig.hideBattlePlanKinds?.length
    ? snapshot.battlePlan.filter(
        (step) => !focusConfig.hideBattlePlanKinds!.includes(step.kind),
      )
    : snapshot.battlePlan;

  const estimatedMinutes = visibleBattlePlan.reduce((sum, step) => {
    const mins = step.kind === "revise" ? 8 : step.kind === "strengthen" ? 15 : step.kind === "academic" ? 20 : 10;
    return sum + mins;
  }, 0);

  // coachBrief was fetched with focusMode="none"; if the user has a preference
  // other than none, re-use the snapshot — the brief content is the same.
  const visiblePriorities = services.studentCoach.gateByFocusMode(intelligence.priorities, focusMode);

  const topInsight = (aiInsights as { detail?: string | null }[])[0];
  const aiSummary = topInsight?.detail ?? null;

  const data: OverviewData = {
    name,
    greeting: greeting(),
    estimatedMinutes,
    aiSummary,
    hero: snapshot.hero,
    battlePlan: visibleBattlePlan.map((step, i) => {
      const { href, minutes } = battlePlanLink(step);
      return {
        id: `${step.kind}-${step.entityId ?? i}`,
        kind: step.kind,
        title: step.title,
        detail: step.detail,
        href,
        minutes,
        entityId: step.entityId ?? null,
      };
    }),
    resumeItems: intelligence.continueLearning.map((r) => ({
      ...r,
      lastTouchedAt: r.lastTouchedAt ? relativeTime(r.lastTouchedAt) : null,
    })),
    recommendations: intelligence.recommendations,
    dailyDigest,
    dailyPlan: intelligence.dailyPlan,
    continueLearning: snapshot.continueLearning[0]
      ? {
          problemId: snapshot.continueLearning[0].problemId,
          title: snapshot.continueLearning[0].title,
          lastTouched: relativeTime(snapshot.continueLearning[0].lastTouchedAt),
        }
      : null,
    revisionQueue: snapshot.revisionQueue.slice(0, 5).map((r) => ({
      problemId: r.problemId,
      title: r.title,
      state: r.state,
    })),
    upcomingAssignments: snapshot.upcomingAssignments.map((a) => ({
      id: a.id,
      title: a.title,
      due: a.dueDate
        ? new Date(a.dueDate).toLocaleDateString("en-US", {
            day: "numeric",
            month: "short",
          })
        : "No date",
      urgent: isDueSoon(a.dueDate),
    })),
    taxonomyProposalsCount: snapshot.taxonomyProposalsCount,
    recentKnowledge: snapshot.recentKnowledge.map((k) => ({
      id: k.id,
      type: k.type,
      title: k.title,
      time: relativeTime(k.createdAt),
    })),
    activity: snapshot.activityTimeline.slice(0, 6).map((item) => ({
      id: item.id,
      text: item.text,
      href: item.href,
      time: relativeTime(item.at),
    })),
    recentSolved: snapshot.recentSolved.map((s) => ({
      problemId: s.problemId,
      title: s.title,
      difficulty: s.difficulty,
    })),
    recentConcepts: snapshot.recentConcepts.map((c) => ({
      id: c.id,
      title: c.title,
      status: c.status,
    })),
    memoryHealth: {
      overallScore: snapshot.memoryHealth.overallScore,
      atRisk: snapshot.memoryHealth.atRisk.map((t) => ({
        id: t.entityId,
        name: t.name,
        healthScore: t.healthScore,
      })),
      neglected: snapshot.memoryHealth.neglected.map((t) => ({
        id: t.entityId,
        name: t.name,
      })),
    },
    forgettingForecast: {
      likelyForgotten: snapshot.forgettingForecast.likelyForgotten.map((f) => ({
        problemId: f.problemId,
        title: f.title,
        score: f.score,
      })),
      atRiskCount: snapshot.forgettingForecast.atRisk.length,
    },
    solvedToday: todayLog?.problems_solved ?? 0,
    notifications,
    missedWork,
    focusMode,
    eveningReview,
    priorities: visiblePriorities,
    missions: intelligence.missions,
    risks: intelligence.risks,
    coachBrief,
    recoveryPlan,
    todayBlocks,
    goalSummaries,
    executionMetrics,
    financeSnapshot,
    plannerState: {
      today: plannerState.today,
      tomorrow: plannerState.tomorrow,
      recent: plannerState.recent,
    },
  };

  return <OverviewClient data={data} />;
}
